name: phoenix
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - pytorch-cuda=11.8
  - pip
  - pip:
    - Pillow>=9.0
    - PyYAML>=6.0
    - lpips>=0.1.4
    - lmdb
    - gdown
    - tqdm
